language: generic
dist: trusty
sudo: required
# cache:
#   directories:
#   - $HOME/.cache/pip

matrix:
  include:  
    # NO C++ test
    # CALLS python tests by hand 
    # (make python test does not work yet)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6
      env:
        - USE_CONDA=true
        - CONDA_PYTHON_VERSION=3.6
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - WITH_GUROBI=0
        - WITH_CPLEX=0


before_install:
  - eval "${MATRIX_EVAL}"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH";
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - conda info -a;
  - conda install -c conda-forge cmake=3.2 conda-build

before_script:
  - eval ${MATRIX_EVAL}
  - $CXX --version
  - cmake --version

script:

  ###############################################
  # shortcuts
  ###############################################
  - $CXX --version
  - $CC --version
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate root
  # need -c ilastik-forge for fastfilters
  - conda build -c conda-forge -c ilastik-forge --python=3.6 --numpy=1.12 conda-recipe


