language: python
dist: trusty
sudo: required
# cache:
#   directories:
#   - $HOME/.cache/pip

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH";
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - conda info -a;
  - conda install -c conda-forge conda-build

script:
  ###############################################
  # shortcuts
  ###############################################
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate root
  # need -c ilastik-forge for fastfilters
  - conda build -c conda-forge -c ilastik-forge conda-recipe

  # todo, add tests
